USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/AMOI/A920W/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6589
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOOTLOADER_BOARD_NAME := A920W

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 6291456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 6291456
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 681574400
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1610612736
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_USE_VIRTUAL_KEYS := true
TARGET_USERIMAGES_USE_EXT4 := true

TARGET_PREBUILT_KERNEL := device/AMOI/A920W/kernel
BOARD_HAS_NO_SELECT_BUTTON := true
BORAD_RECOVEY_USE_CHINESE := true
BOARD_USE_CUSTOM_EVENTS := true
TARGET_RECOVERY_INITRC := device/AMOI/A920W/recovery/recovery.rc
TARGET_RECOVERY_FSTAB := device/AMOI/A920W/recovery/recovery.fstab
CWM_EMMC_BOOT_DEVICE_NAME := /dev/bootimg
CWM_EMMC_BOOT_DEVICE_SIZE := 0x00600000
CWM_EMMC_RECOVERY_DEVICE_NAME := /dev/recovery
CWM_EMMC_RECOVERY_DEVICE_SIZE := 0x00600000
CWM_EMMC_UBOOT_DEVICE_NAME := /dev/uboot
CWM_EMMC_UBOOT_DEVICE_SIZE := 0x00060000
DEVICE_RESOLUTION := 1080x1920
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 1920
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/gadget/lun%d/file

# EXT4
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_USES_MMCUTILS := true
# Use this flag if the board has a ext4 partition larger than 2gb
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_CUSTOM_BOOTIMG_MK := device/AMOI/A920W/custombootimg.mk

#suda
BORAD_RECOVEY_USE_CHINESE := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"chinese/font_18x24.h\"


